FIX: valign attribute not respected
foundation/foundation-emails pull request #1002
Opened 2020-04-24 13:38 UTC by putzwasser

_normalize.scss hardcoded `vertical-align: top;` for `td` and `th`. This breaks setting `<column valign="bottom>"`.

2020-04-24 13:59 UTC, DanielRuf commented
This is probably not the correct solution. There was probably some regression in the columns element.

The affected code was not changed for 5 years, see https://github.com/foundation/foundation-emails/blame/develop/scss/components/_normalize.scss#L85

2020-04-24 15:31 UTC, DanielRuf reviewed
We will have to test if the email clients support `:not`.

2020-08-01 22:26 UTC, DanielRuf commented
The support for `:not` is not so good: https://www.caniemail.com/features/css-pseudo-class-not/

2020-08-01 22:27 UTC, DanielRuf requested changes
Needs different approach.

See https://www.caniemail.com/features/css-pseudo-class-not/

2020-08-03 13:13 UTC, joeworkman commented
This pull request has been mentioned on **Foundation Open Source Community**. There might be relevant details there:

https://foundation.discourse.group/t/foundation-emails-vertical-alignment-not-working/3139/2

2020-08-03 22:21 UTC, nikitasol commented
I have just created a pull request with a different approach which works:

https://github.com/foundation/foundation-emails/pull/1016/commits/fb07ed5da602695e4193d36358db4a2e2eb5aa0a

2020-08-04 08:04 UTC, DanielRuf commented
Thanks, but please link the PR URL and not the commit URL so we can find it easier =)

2020-08-10 12:58 UTC, nikitasol commented
Here you go, @DanielRuf : https://github.com/foundation/foundation-emails/pull/1016

2020-08-10 13:21 UTC, closed without merging