Use percent line-height four Outlook 2007/10/13 (Fix #590)
foundation/foundation-emails pull request #683
Opened 2017-01-20 15:12 UTC by jsit

2017-02-22 18:00 UTC, xerxesj commented
Nice fix, but I noticed that the percentage based line-height was adding a bunch of bottom padding to all my buttons. If you add a `line-height: 100%;` to both `<a>` and `<td>` tags within `table.button` fixes the issue.

``` css
table.button {
  td,
  a {
    line-height: 100%;
  }
}
```

2017-02-22 18:12 UTC, IamManchanda requested changes

2017-02-22 18:12 UTC, IamManchanda commented on scss/settings/_settings.scss
> +$global-line-height: 130%;
Settings file is generated automatically 

Revert from here and change it here => https://github.com/zurb/foundation-emails/blob/develop/scss/components/_typography.scss#L27

2017-02-22 18:12 UTC, IamManchanda commented on scss/settings/_settings.scss
> +$lead-line-height: 160%;
Revert from here and change it here => https://github.com/zurb/foundation-emails/blob/develop/scss/components/_typography.scss#L91

2017-02-24 16:45 UTC, jsit commented
Fixed, @IamManchanda. Thanks.

2017-04-27 23:58 UTC, merged

2017-04-27 23:58 UTC, tdhartwick commented
nice! Thanks!