Updated the installation to use npx
foundation/foundation-emails pull request #839
Opened 2017-10-25 17:45 UTC by woodyrew

npx ships with npm as of v5.2.0

Before submitting a pull request, make sure it's targeting the right branch:

- For fixes to Ink 1.0, use `master`.
- For fixes to Foundation for Emails 2, use `v2.0`.

Happy coding! :)

2019-11-01 09:50 UTC, DanielRuf requested changes

2019-11-01 09:50 UTC, DanielRuf commented on docs/pages/sass-guide.md
> +npm install --global npx
This is not really needed anymore.

2019-11-01 09:50 UTC, DanielRuf commented on docs/pages/sass-guide.md
> +sudo npm install --global npx
Not needed.

2019-11-01 10:20 UTC, woodyrew commented
Thanks for the review @DanielRuf. I've made changes as requested.

2019-11-01 10:39 UTC, DanielRuf requested changes

2019-11-01 10:39 UTC, DanielRuf commented on docs/pages/sass-guide.md
> +After your project has been installed, run `cd project`, where `project` is the name of the project just created. Install the dependancies:
dependancies => dependencies

2019-11-01 11:21 UTC, woodyrew commented on docs/pages/sass-guide.md
> +After your project has been installed, run `cd project`, where `project` is the name of the project just created. Install the dependancies:
Fixed

2019-11-01 12:34 UTC, DanielRuf requested changes

2019-11-01 12:34 UTC, DanielRuf commented on docs/pages/sass-guide.md
> +Run the Foundation CLI as a one-off command using [npx](https://www.npmjs.com/package/npx), it’s super easy to fire up a blank Foundation for Emails project. Move into the folder you store your proje
```suggestion
Run the Foundation CLI as a one-off command using [npx](https://www.npmjs.com/package/npx), it's super easy to fire up a blank Foundation for Emails project. Move into the folder you store your projects in, and then run this command:
```

2019-11-01 12:36 UTC, DanielRuf commented
In general I would also keep the old part as this is also an option (for those wo can not or do not want to use npx and want to install it globally.

So please a the old part too. The recommended way is npx and yarn.

2019-11-23 21:52 UTC, DanielRuf commented
> So please a the old part too. The recommended way is npx and yarn.

2019-11-28 13:07 UTC, woodyrew commented
Sounds like you have a good idea how you'd like it to be conveyed. Feel free to use this PR as a starting point. :smile:

2019-11-28 13:07 UTC, closed without merging